#+STARTUP: showall

TRUFA (Transcriptomes User-Friendly Analysis) is a free webserver designed to
help you perform RNA-seq analysis.

Joint work done by:

 - Advanced Computing & e-Science Research Line at Instituto de Física de
   Cantabria (IFCA)
 - Museo Nacional de Ciencias Naturales

* Fast Install

  *PREREQUISITES*: You need to have installed Python with modules /webpy/,
  /bcrypt/, /pysqlite2/ and /htpasswd/.

  Copy the file /config.py.example/ to /config.py/. This file should be edited
  to setup the web server.

  #+begin_src bash
  cp config.py.example config.py
  #+end_src

  Edit the file /config.py/ and set the variables ~LAUNCHER_TOOL~ and
  ~LAUNCHER_LIB~ to point to the TRUFA server side package. This package has the
  tools to launch workflows in the web server, and it should be installed in the
  same host. The TRUFA server package uses a scheduling system for clusters, but
  for testing you can install /trufa-server-null/ that mocks the necesary to
  deploy the web frontend.

  Edit the file /config.py/ and set the variables ~SERVER_CRT~ and ~SERVER_KEY~
  to point to valid SSL certificate and key. You can create a self-signed SSL
  Certificate which can be used for testing purposes with:

  #+begin_src bash
  openssl genrsa -des3 -out trufa.key 1024
  openssl req -new -key trufa.key -out trufa.csr
  cp trufa.key trufa.key.org
  openssl rsa -in trufa.key.org -out trufa.key
  openssl x509 -req -days 365 -in trufa.csr -signkey trufa.key -out trufa.crt
  #+end_src

  Edit the file /config.py/ and set the variable ~DATADIR~ to point to a folder
  where you have write permission.

  Edit the file /config.py/ and set the initial test user with variables
  ~DB_TEST_USER~ and ~DB_TEST_PASS~.

  You should edit other variables at /config.py/ but these are the
  minimum. After that, you can start the web server with:

  #+begin_src bash
  python joborama.py
  #+end_src

  And then open the main page in your web browser, usually
  https://localhost:8080

  *DISCLAIMER*: The Fast Install is enough to see and test TRUFA web, but lots
  of features will be disabled or they won't work (e.g: workflow submit, file
  explorer, ... etc)

* Acknowledgments
  - Bootstrap 2.3.2 [[http://twitter.github.io/bootstrap/]]
  - JQuery 2.0.1 [[http://jquery.com/]]
  - Web.py http://webpy.org/
  - Sqlite https://sqlite.org/
